[project]
name = "vdu-benchmarks"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "datasets>=5.0.1",
    "jupyter>=1.1.1",
    "langchain>=1.4.0",
    "llama-index>=0.14.24",
    "loguru>=0.7.3",
    "matplotlib>=3.11.1",
    "openai>=2.54.0",
    "pandas>=3.0.5",
    "pillow>=12.3.0",
    "pydantic>=2.13.5",
    "pydantic-settings>=2.15.0",
    "tenacity>=9.1.4",
]

[dependency-groups]
dev = [
    "ruff>=0.16.6",
]

[tool.ruff]
line-length = 88
target-version = "py313"

[tool.ruff.lint]
select = ["I"]

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "auto"

